# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 575)
        MainWindow.setMinimumSize(QtCore.QSize(850, 575))
        MainWindow.setMaximumSize(QtCore.QSize(850, 575))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cnv_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.cnv_view.setGeometry(QtCore.QRect(10, 10, 541, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cnv_view.sizePolicy().hasHeightForWidth())
        self.cnv_view.setSizePolicy(sizePolicy)
        self.cnv_view.setMinimumSize(QtCore.QSize(541, 561))
        self.cnv_view.setMaximumSize(QtCore.QSize(541, 561))
        self.cnv_view.setObjectName("cnv_view")
        self.algorythm = QtWidgets.QComboBox(self.centralwidget)
        self.algorythm.setGeometry(QtCore.QRect(590, 10, 231, 22))
        self.algorythm.setObjectName("algorythm")
        self.algorythm.addItem("")
        self.algorythm.addItem("")
        self.algorythm.addItem("")
        self.algorythm.addItem("")
        self.algorythm.addItem("")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setGeometry(QtCore.QRect(560, 200, 281, 231))
        self.main_tab.setMaximumSize(QtCore.QSize(16777215, 16777204))
        self.main_tab.setObjectName("main_tab")
        self.cirlce = QtWidgets.QWidget()
        self.cirlce.setObjectName("cirlce")
        self.inside_tab_cirlce = QtWidgets.QTabWidget(self.cirlce)
        self.inside_tab_cirlce.setGeometry(QtCore.QRect(0, 0, 271, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.inside_tab_cirlce.setPalette(palette)
        self.inside_tab_cirlce.setObjectName("inside_tab_cirlce")
        self.draw_circle = QtWidgets.QWidget()
        self.draw_circle.setObjectName("draw_circle")
        self.xc_circle = QtWidgets.QDoubleSpinBox(self.draw_circle)
        self.xc_circle.setGeometry(QtCore.QRect(140, 10, 71, 22))
        self.xc_circle.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.xc_circle.setMaximum(561.0)
        self.xc_circle.setObjectName("xc_circle")
        self.lbl_xc_circle = QtWidgets.QLabel(self.draw_circle)
        self.lbl_xc_circle.setGeometry(QtCore.QRect(60, 10, 51, 16))
        self.lbl_xc_circle.setObjectName("lbl_xc_circle")
        self.yc_circle = QtWidgets.QDoubleSpinBox(self.draw_circle)
        self.yc_circle.setGeometry(QtCore.QRect(140, 60, 71, 22))
        self.yc_circle.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.yc_circle.setMaximum(541.0)
        self.yc_circle.setObjectName("yc_circle")
        self.lbl_yc_circle = QtWidgets.QLabel(self.draw_circle)
        self.lbl_yc_circle.setGeometry(QtCore.QRect(60, 60, 51, 16))
        self.lbl_yc_circle.setObjectName("lbl_yc_circle")
        self.lbl_radius = QtWidgets.QLabel(self.draw_circle)
        self.lbl_radius.setGeometry(QtCore.QRect(60, 110, 41, 16))
        self.lbl_radius.setObjectName("lbl_radius")
        self.radius = QtWidgets.QDoubleSpinBox(self.draw_circle)
        self.radius.setGeometry(QtCore.QRect(140, 110, 71, 22))
        self.radius.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.radius.setMaximum(541.0)
        self.radius.setObjectName("radius")
        self.btn_get_circle = QtWidgets.QPushButton(self.draw_circle)
        self.btn_get_circle.setGeometry(QtCore.QRect(60, 150, 151, 23))
        self.btn_get_circle.setObjectName("btn_get_circle")
        self.inside_tab_cirlce.addTab(self.draw_circle, "")
        self.spectre_circle = QtWidgets.QWidget()
        self.spectre_circle.setObjectName("spectre_circle")
        self.lbl_min_radius = QtWidgets.QLabel(self.spectre_circle)
        self.lbl_min_radius.setGeometry(QtCore.QRect(50, 10, 71, 20))
        self.lbl_min_radius.setObjectName("lbl_min_radius")
        self.min_radius = QtWidgets.QDoubleSpinBox(self.spectre_circle)
        self.min_radius.setGeometry(QtCore.QRect(160, 10, 71, 22))
        self.min_radius.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.min_radius.setMaximum(561.0)
        self.min_radius.setObjectName("min_radius")
        self.lbl_num_circle = QtWidgets.QLabel(self.spectre_circle)
        self.lbl_num_circle.setGeometry(QtCore.QRect(50, 100, 91, 31))
        self.lbl_num_circle.setObjectName("lbl_num_circle")
        self.btn_get_circle_spectre = QtWidgets.QPushButton(self.spectre_circle)
        self.btn_get_circle_spectre.setGeometry(QtCore.QRect(50, 150, 181, 23))
        self.btn_get_circle_spectre.setObjectName("btn_get_circle_spectre")
        self.lbl_step_radius = QtWidgets.QLabel(self.spectre_circle)
        self.lbl_step_radius.setGeometry(QtCore.QRect(50, 49, 81, 31))
        self.lbl_step_radius.setObjectName("lbl_step_radius")
        self.step_radius = QtWidgets.QSpinBox(self.spectre_circle)
        self.step_radius.setGeometry(QtCore.QRect(160, 60, 71, 22))
        self.step_radius.setObjectName("step_radius")
        self.num_circle = QtWidgets.QSpinBox(self.spectre_circle)
        self.num_circle.setGeometry(QtCore.QRect(160, 110, 71, 22))
        self.num_circle.setObjectName("num_circle")
        self.inside_tab_cirlce.addTab(self.spectre_circle, "")
        self.main_tab.addTab(self.cirlce, "")
        self.ellipse = QtWidgets.QWidget()
        self.ellipse.setObjectName("ellipse")
        self.inside_tab_ellipse = QtWidgets.QTabWidget(self.ellipse)
        self.inside_tab_ellipse.setGeometry(QtCore.QRect(0, 0, 271, 201))
        self.inside_tab_ellipse.setObjectName("inside_tab_ellipse")
        self.draw_ellipse = QtWidgets.QWidget()
        self.draw_ellipse.setObjectName("draw_ellipse")
        self.yc_ellipse = QtWidgets.QDoubleSpinBox(self.draw_ellipse)
        self.yc_ellipse.setGeometry(QtCore.QRect(140, 60, 71, 22))
        self.yc_ellipse.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.yc_ellipse.setMaximum(541.0)
        self.yc_ellipse.setObjectName("yc_ellipse")
        self.lbl_yc_ellipse = QtWidgets.QLabel(self.draw_ellipse)
        self.lbl_yc_ellipse.setGeometry(QtCore.QRect(60, 60, 51, 16))
        self.lbl_yc_ellipse.setObjectName("lbl_yc_ellipse")
        self.lbl_xc_ellipse = QtWidgets.QLabel(self.draw_ellipse)
        self.lbl_xc_ellipse.setGeometry(QtCore.QRect(60, 10, 51, 16))
        self.lbl_xc_ellipse.setObjectName("lbl_xc_ellipse")
        self.btn_get_ellipse = QtWidgets.QPushButton(self.draw_ellipse)
        self.btn_get_ellipse.setGeometry(QtCore.QRect(60, 150, 151, 23))
        self.btn_get_ellipse.setObjectName("btn_get_ellipse")
        self.xc_ellipse = QtWidgets.QDoubleSpinBox(self.draw_ellipse)
        self.xc_ellipse.setGeometry(QtCore.QRect(140, 10, 71, 22))
        self.xc_ellipse.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.xc_ellipse.setMaximum(561.0)
        self.xc_ellipse.setObjectName("xc_ellipse")
        self.a = QtWidgets.QDoubleSpinBox(self.draw_ellipse)
        self.a.setGeometry(QtCore.QRect(60, 100, 62, 22))
        self.a.setObjectName("a")
        self.b = QtWidgets.QDoubleSpinBox(self.draw_ellipse)
        self.b.setGeometry(QtCore.QRect(170, 100, 62, 22))
        self.b.setObjectName("b")
        self.lbl_a = QtWidgets.QLabel(self.draw_ellipse)
        self.lbl_a.setGeometry(QtCore.QRect(40, 100, 21, 16))
        self.lbl_a.setObjectName("lbl_a")
        self.lbl_b = QtWidgets.QLabel(self.draw_ellipse)
        self.lbl_b.setGeometry(QtCore.QRect(150, 100, 21, 16))
        self.lbl_b.setObjectName("lbl_b")
        self.inside_tab_ellipse.addTab(self.draw_ellipse, "")
        self.spectre_ellipse = QtWidgets.QWidget()
        self.spectre_ellipse.setObjectName("spectre_ellipse")
        self.min_a = QtWidgets.QDoubleSpinBox(self.spectre_ellipse)
        self.min_a.setGeometry(QtCore.QRect(50, 10, 62, 22))
        self.min_a.setObjectName("min_a")
        self.min_b = QtWidgets.QDoubleSpinBox(self.spectre_ellipse)
        self.min_b.setGeometry(QtCore.QRect(180, 10, 62, 22))
        self.min_b.setObjectName("min_b")
        self.lbl_min_a = QtWidgets.QLabel(self.spectre_ellipse)
        self.lbl_min_a.setGeometry(QtCore.QRect(10, 10, 47, 20))
        self.lbl_min_a.setObjectName("lbl_min_a")
        self.lbl_min_b = QtWidgets.QLabel(self.spectre_ellipse)
        self.lbl_min_b.setGeometry(QtCore.QRect(140, 10, 47, 20))
        self.lbl_min_b.setObjectName("lbl_min_b")
        self.lbl_step = QtWidgets.QLabel(self.spectre_ellipse)
        self.lbl_step.setGeometry(QtCore.QRect(90, 40, 81, 21))
        self.lbl_step.setObjectName("lbl_step")
        self.step_a = QtWidgets.QSpinBox(self.spectre_ellipse)
        self.step_a.setGeometry(QtCore.QRect(50, 70, 61, 22))
        self.step_a.setObjectName("step_a")
        self.lbl_num_ellipse = QtWidgets.QLabel(self.spectre_ellipse)
        self.lbl_num_ellipse.setGeometry(QtCore.QRect(30, 110, 91, 21))
        self.lbl_num_ellipse.setObjectName("lbl_num_ellipse")
        self.step_b = QtWidgets.QSpinBox(self.spectre_ellipse)
        self.step_b.setGeometry(QtCore.QRect(180, 70, 61, 22))
        self.step_b.setObjectName("step_b")
        self.lbl_step_a = QtWidgets.QLabel(self.spectre_ellipse)
        self.lbl_step_a.setGeometry(QtCore.QRect(30, 70, 21, 21))
        self.lbl_step_a.setObjectName("lbl_step_a")
        self.lbl_step_b = QtWidgets.QLabel(self.spectre_ellipse)
        self.lbl_step_b.setGeometry(QtCore.QRect(160, 70, 21, 21))
        self.lbl_step_b.setObjectName("lbl_step_b")
        self.num_ellipse = QtWidgets.QSpinBox(self.spectre_ellipse)
        self.num_ellipse.setGeometry(QtCore.QRect(180, 110, 61, 21))
        self.num_ellipse.setObjectName("num_ellipse")
        self.btn_get_ellipse_spectre = QtWidgets.QPushButton(self.spectre_ellipse)
        self.btn_get_ellipse_spectre.setGeometry(QtCore.QRect(50, 150, 181, 23))
        self.btn_get_ellipse_spectre.setObjectName("btn_get_ellipse_spectre")
        self.inside_tab_ellipse.addTab(self.spectre_ellipse, "")
        self.main_tab.addTab(self.ellipse, "")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(600, 460, 211, 31))
        self.btn_delete.setObjectName("btn_delete")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(600, 510, 211, 31))
        self.btn_exit.setObjectName("btn_exit")
        self.btn_line_color = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_color.setGeometry(QtCore.QRect(590, 60, 121, 31))
        self.btn_line_color.setObjectName("btn_line_color")
        self.line_color_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.line_color_view.setGeometry(QtCore.QRect(730, 60, 91, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.line_color_view.setPalette(palette)
        self.line_color_view.setObjectName("line_color_view")
        self.btn_bg_color = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bg_color.setGeometry(QtCore.QRect(590, 110, 121, 31))
        self.btn_bg_color.setObjectName("btn_bg_color")
        self.bg_color_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.bg_color_view.setGeometry(QtCore.QRect(730, 110, 91, 31))
        self.bg_color_view.setObjectName("bg_color_view")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        self.inside_tab_cirlce.setCurrentIndex(0)
        self.inside_tab_ellipse.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Рисование окружностей/эллипсов"))
        self.algorythm.setItemText(0, _translate("MainWindow", "Каноническое уравнение"))
        self.algorythm.setItemText(1, _translate("MainWindow", "Параметрическое уравнение"))
        self.algorythm.setItemText(2, _translate("MainWindow", "Брезенхем"))
        self.algorythm.setItemText(3, _translate("MainWindow", "Алгоритм средней точки"))
        self.algorythm.setItemText(4, _translate("MainWindow", "Библиотечный алгоритм"))
        self.lbl_xc_circle.setText(_translate("MainWindow", "X центра:"))
        self.lbl_yc_circle.setText(_translate("MainWindow", "Y центра:"))
        self.lbl_radius.setText(_translate("MainWindow", "Радиус"))
        self.btn_get_circle.setText(_translate("MainWindow", "Построить окружность"))
        self.inside_tab_cirlce.setTabText(self.inside_tab_cirlce.indexOf(self.draw_circle), _translate("MainWindow", "Рисование"))
        self.lbl_min_radius.setText(_translate("MainWindow", "Мин. радиус:"))
        self.lbl_num_circle.setText(_translate("MainWindow", "Кол-во\n"
"окружностей:"))
        self.btn_get_circle_spectre.setText(_translate("MainWindow", "Построить спектр"))
        self.lbl_step_radius.setText(_translate("MainWindow", "Шаг изменения\n"
"радиуса:"))
        self.inside_tab_cirlce.setTabText(self.inside_tab_cirlce.indexOf(self.spectre_circle), _translate("MainWindow", "Спектр"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.cirlce), _translate("MainWindow", "Окружность"))
        self.lbl_yc_ellipse.setText(_translate("MainWindow", "Y центра:"))
        self.lbl_xc_ellipse.setText(_translate("MainWindow", "X центра:"))
        self.btn_get_ellipse.setText(_translate("MainWindow", "Построить эллипс"))
        self.lbl_a.setText(_translate("MainWindow", "a:"))
        self.lbl_b.setText(_translate("MainWindow", "b:"))
        self.inside_tab_ellipse.setTabText(self.inside_tab_ellipse.indexOf(self.draw_ellipse), _translate("MainWindow", "Рисование"))
        self.lbl_min_a.setText(_translate("MainWindow", "Мин. a:"))
        self.lbl_min_b.setText(_translate("MainWindow", "Мин. b:"))
        self.lbl_step.setText(_translate("MainWindow", "Шаг изменения:"))
        self.lbl_num_ellipse.setText(_translate("MainWindow", "Кол-во эллипсов:"))
        self.lbl_step_a.setText(_translate("MainWindow", "a:"))
        self.lbl_step_b.setText(_translate("MainWindow", "b:"))
        self.btn_get_ellipse_spectre.setText(_translate("MainWindow", "Построить спектр"))
        self.inside_tab_ellipse.setTabText(self.inside_tab_ellipse.indexOf(self.spectre_ellipse), _translate("MainWindow", "Спектр"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.ellipse), _translate("MainWindow", "Эллипс"))
        self.btn_delete.setText(_translate("MainWindow", "Очистить холст"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))
        self.btn_line_color.setText(_translate("MainWindow", "Выбрать цвет линии"))
        self.btn_bg_color.setText(_translate("MainWindow", "Выбрать цвет фона"))

